# Generated by Django 5.2.4 on 2025-07-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_azienda', models.CharField(max_length=100)),
                ('id_servizio_azienda', models.CharField(max_length=100)),
                ('nome_veicolo', models.CharField(max_length=100)),
                ('id_device', models.CharField(max_length=50)),
                ('nome_entita', models.CharField(max_length=100)),
                ('secret_key', models.CharField(max_length=100)),
                ('sottogruppo', models.CharField(max_length=50)),
            ],
        ),
    ]
