# Generated by Django 5.2.4 on 2025-07-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utente',
            options={'ordering': ['nome', 'cognome'], 'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
